version: '3'

services:
  mongodb:
    image: mongo:3.6
    volumes:
      - mongo_data:/data/db
    networks:
      - frontend

  customer:
    build: ./test
    ports:
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:

volumes:
  mongo_data:
